stages:
  - release

variables:
  DOCKER_IMAGE: "ghcr.io/git-releaser/git-releaser:dev-202312092322"
  GIT_RELEASER_PROVIDER: "gitlab"
  GIT_RELEASER_USER_ID: "11274974"
  GIT_RELEASER_TOKEN: $PAT
  GIT_RELEASER_PROJECT_URL: "https://gitlab.com/thomasstxyz/gh-actions-workflow-test"
  GIT_RELEASER_PROJECT_ID: $CI_PROJECT_ID

run-release:
  stage: release
  script:
    - git clone $GIT_RELEASER_PROJECT_URL
    - cd gh-actions-workflow-test
    - /git-releaser update
  image:
    name: $DOCKER_IMAGE
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
