stages:
  - release

run-release:
  variables:
    DOCKER_IMAGE: "ghcr.io/git-releaser/git-releaser:dev-202312092322"
    GIT_RELEASER_PROVIDER: "gitlab"
    GIT_RELEASER_USER_ID: "thomasstxyz"
    GIT_RELEASER_TOKEN: $PAT  # PAT is saved as a CI/CD variable
    GIT_RELEASER_PROJECT_URL: "https://$GIT_RELEASER_USER_ID:$GIT_RELEASER_TOKEN@gitlab.com/thomasstxyz/gh-actions-workflow-test"
    GIT_RELEASER_PROJECT_ID: $CI_PROJECT_ID
  stage: release
  script:
    - mkdir repo ; cd repo
    - git clone $GIT_RELEASER_PROJECT_URL .
    - /git-releaser update
  image:
    name: $DOCKER_IMAGE
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
