apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: default
spec:
  replicas: 3
  template:
    spec:
      containers:
        - image: 'docker.io/kostiscodefresh/simple-web-app:3d9b390'
          name: webserver-simple
