name: CI/CD

on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  release-please:
    if: github.event_name == 'push'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: package1
          token: ${{ secrets.GITHUB_TOKEN }}

  terraform_dryrun_demo:
    name: "[demo] Dry-run Terraform deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: demo
          action: apply
          apply: false

  terraform_apply_demo:
    name: "[demo] Apply Terraform deployment"
    needs:
      - terraform_dryrun_demo
      - release-please
    if: needs.release-please.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    environment: demo
    concurrency:
      group: demo
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: demo
          action: apply
          apply: true

  terraform_dryrun_prod:
    name: "[prod] Dry-run Terraform deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: prod
          action: apply
          apply: false

  terraform_apply_prod:
    name: "[prod] Apply Terraform deployment"
    needs:
      - terraform_apply_demo
      - terraform_dryrun_prod
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: prod
    concurrency:
      group: prod
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: prod
          action: apply
          apply: true
