name: CI/CD

on:
  release:
    types: [published]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  release-please:
    if: github.event_name == 'push'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: package1
          token: ${{ secrets.GITHUB_TOKEN }}

  terraform_dryrun_demo:
    name: "[dry-run] apply demo environment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: demo
          action: apply
          apply: false

  terraform_apply_demo:
    name: "apply demo environment"
    needs:
      - terraform_dryrun_demo
      - release-please
    if: needs.release-please.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    environment: demo
    concurrency:
      group: demo
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: demo
          action: apply
          apply: true

  terraform_dryrun_prod:
    name: "[dry-run] apply prod environment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: prod
          action: apply
          apply: false

  terraform_apply_prod:
    name: "apply prod environment"
    needs:
      - terraform_apply_demo
      - terraform_dryrun_prod
      - release-please
    if: needs.release-please.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    environment: prod
    concurrency:
      group: prod
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: prod
          action: apply
          apply: true
