name: deploy
run-name: "deploy ${{ github.ref_name }}"

on:
  push:
    branches:
      - "demo"
      - "prod"

jobs:
  terraform:
    uses: ./.github/workflows/reusable-terraform-workflow.yaml
    with:
      environment: "${{ github.ref_name }}"
      action: "apply"
      apply: "true"
    secrets: inherit
