name: Reusable deploy workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment which should be started/stopped'
        required: true
        default: "lab"
        type: string
      action:
        description: 'Action to be taken'
        required: true
        default: "apply"
        type: string
      apply:
        type: boolean
        description: 'Apply the configuration?'
        required: true
        default: false
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment which should be started/stopped'
        required: true
        default: "lab"
        type: environment
      action:
        description: 'Action to be taken'
        required: true
        default: "apply"
        type: choice
        options:
          - "apply"
          - "destroy"
      apply:
        type: boolean
        description: 'Apply the configuration?'
        required: true
        default: false

jobs:
  terraform:
    name: "Dry-run Terraform"
    if: inputs.apply == false || (github.event_name == 'release' && inputs.apply == true) || (github.event_name == 'workflow_dispatch' && inputs.apply == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Dry-run Terraform"
        uses: "./.github/actions/terraform.yml"
        with:
          environment: ${{ inputs.environment }}
          action: ${{ inputs.action }}
          apply: ${{ inputs.apply }}

  terraform_apply:
    name: "Apply Terraform"
    if: inputs.apply == true && (github.event_name == 'release' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: "Apply Terraform"
        uses: "./.github/actions/terraform.yml"
        with:
          environment: ${{ inputs.environment }}
          action: ${{ inputs.action }}
          apply: ${{ inputs.apply }}
