name: Deployment

on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  runs-on: ubuntu-latest

jobs:
  validate_terraform_demo_environment:
    name: "[demo] Validate Terraform code"
    steps:
      - uses: actions/checkout@v3
      - name: "Terraform plan (demo environment)"
        run: |
          echo "environment: demo"
          echo "running 'terraform validate'..."
  plan_deploy_to_demo_environment:
    name: "[demo] Plan Terraform deployment"
    steps:
      - uses: actions/checkout@v3
      - name: "Terraform plan (demo environment)"
        run: |
          echo "environment: demo"
          echo "running 'terraform plan'..."
  deploy_to_demo_environment:
    if: github.event_name == 'release'
    name: "[demo] Apply Terraform deployment"
    environment: demo
    steps:
      - uses: actions/checkout@v3
      - name: "Terraform apply (demo environment)"
        run: |
          echo "environment: demo"
          echo "running 'terraform apply'..."


  plan_deploy_to_prod_environment:
    name: "[prod] Plan Terraform deployment"
    steps:
      - uses: actions/checkout@v3
      - name: "Terraform plan (prod environment)"
        run: |
          echo "environment: prod"
          echo "running 'terraform plan'..."
  deploy_to_prod_environment:
    if: github.event_name == 'release'
    needs: deploy_to_demo_environment
    name: "[prod] Apply Terraform deployment"
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: "Terraform apply (prod environment)"
        run: |
          echo "environment: prod"
          echo "running 'terraform apply'..."
