name: Dispatch Terraform - apply/destroy
run-name: "${{ inputs.action }} ${{ inputs.environment }} environment by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment which should be started/stopped'
        required: true
        default: "lab"
        type: environment
      action:
        description: 'Action to be taken'
        required: true
        default: "apply"
        type: choice
        options:
          - "apply"
          - "destroy"
      apply:
        type: boolean
        description: 'Apply the configuration?'
        required: true
        default: false

concurrency:
  group: ${{ inputs.environment }}

jobs:
  terraform_plan:
    name: "terraform plan ${{ inputs.action }} ${{ inputs.environment }} environment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: ${{ inputs.environment }}
          action: ${{ inputs.action }}
          apply: false

  terraform_apply:
    if: inputs.apply == true
    name: "terraform ${{ inputs.action }} ${{ inputs.environment }} environment"
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: ${{ inputs.environment }}
          action: ${{ inputs.action }}
          apply: ${{ inputs.apply }}
