name: Deployment

on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ENVIRONMENT_NAME_DEMO: demo
  ENVIRONMENT_NAME_PROD: prod

jobs:
  plan_deploy_to_demo_environment:
    name: "Plan Terraform deployment (demo env)"  # "${{ env.ENVIRONMENT_NAME_DEMO }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Terraform plan (${{ env.ENVIRONMENT_NAME_DEMO }} environment)"
        run: |
          echo "environment: ${{ env.ENVIRONMENT_NAME_DEMO }}"
          echo "running 'terraform plan'..."


  deploy_to_demo_environment:
    if: github.event_name == 'release'
    name: "Apply Terraform deployment (${{ env.ENVIRONMENT_NAME_DEMO }} env)"
    runs-on: ubuntu-latest
    environment: demo  # "${{ env.ENVIRONMENT_NAME_DEMO }}"

    steps:
      - uses: actions/checkout@v3

      - name: "Terraform apply (${{ env.ENVIRONMENT_NAME_DEMO }} environment)"
        run: |
          echo "environment: ${{ env.ENVIRONMENT_NAME_DEMO }}"
          echo "running 'terraform apply'..."
