name: Deployment

on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  plan_deploy_to_demo_environment:
    if: github.event_name != 'release'
    name: "[demo] Dry-run Terraform deployment"
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      environment: demo
      action: apply
      apply: false
    secrets: inherit

  deploy_to_demo_environment:
    if: github.event_name == 'release'
    name: "[demo] Apply Terraform deployment"
    id: deploy_demo
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      environment: demo
      action: apply
      apply: true
    secrets: inherit

  plan_deploy_to_prod_environment:
    if: github.event_name != 'release'
    name: "[prod] Dry-run Terraform deployment"
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      environment: prod
      action: apply
      apply: false
    secrets: inherit

  deploy_to_prod_environment:
    if: github.event_name == 'release'
    needs: deploy_demo
    name: "[prod] Apply Terraform deployment"
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      environment: prod
      action: apply
      apply: true
    secrets: inherit
