name: Deployment

on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  plan_deploy_to_demo_environment:
    name: "[demo] Plan Terraform deployment"
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      environment: demo
      action: apply
      apply: false
    secrets: inherit

  deploy_to_demo_environment:
    if: github.event_name == 'release'
    name: "[demo] Apply Terraform deployment"
    # environment: demo
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      environment: demo
      action: apply
      apply: true
    secrets: inherit

  plan_deploy_to_prod_environment:
    name: "[prod] Plan Terraform deployment"
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      environment: prod
      action: apply
      apply: false
    secrets: inherit

  deploy_to_prod_environment:
    if: github.event_name == 'release'
    name: "[prod] Apply Terraform deployment"
    # environment: prod
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      environment: prod
      action: apply
      apply: true
    secrets: inherit
