name: Deployment

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy_demo:
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: deploy
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/thomasstxyz/gh-actions-workflow-test/actions/workflows/deploy_env.yml/dispatches \
            -d '{"ref":"main","inputs":{"environment":"demo","action":"apply","apply":"false"}}'
