name: Deployment

on:
  release:
    types: [published]
  push:
    branches: ["main"]
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: ["main"]

env:
  ENVIRONMENT_NAME_DEMO: demo
  ENVIRONMENT_NAME_PROD: prod

jobs:
  plan_deploy_to_demo_environment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Terraform plan (${{ env.ENVIRONMENT_NAME_DEMO }} environment)"
        run: |
          echo "environment: ${{ env.ENVIRONMENT_NAME_DEMO }}"
          echo "running 'terraform plan'..."


  deploy_to_demo_environment:
    if: github.event_name == 'release'

    runs-on: ubuntu-latest

    environment: demo  # "${{ env.ENVIRONMENT_NAME_DEMO }}"

    steps:
      - uses: actions/checkout@v3

      - name: "Terraform apply (${{ env.ENVIRONMENT_NAME_DEMO }} environment)"
        run: |
          echo "environment: ${{ env.ENVIRONMENT_NAME_DEMO }}"
          echo "running 'terraform apply'..."
