name: Deploy terraform
run-name: "Deploy to ${{ github.ref_name }} environment"

on:
  push:
    branches:
      - "demo"
      - "prod"

concurrency: ${{ github.ref_name }}

jobs:
  terraform:
    uses: ./.github/workflows/reusable-terraform-workflow.yaml
    with:
      environment: "${{ github.ref_name }}"
      action: "apply"
      apply: "true"
    secrets: inherit
