name: Reusable deploy workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment which should be started/stopped'
        required: true
        default: "lab"
        type: choice
        options:
          - "lab"
          - "dev"
          - "demo"
          - "prod"
      action:
        description: 'Action to be taken'
        required: true
        default: "apply"
        type: choice
        options:
          - "apply"
          - "destroy"
      apply:
        type: boolean
        description: 'Apply the configuration?'
        required: true
        default: false
  workflow_call:
    inputs:
      environment:
        description: 'Environment which should be started/stopped'
        required: true
        default: "lab"
        type: string
      action:
        description: 'Action to be taken'
        required: true
        default: "apply"
        type: string
      apply:
        type: boolean
        description: 'Apply the configuration?'
        required: true
        default: false

jobs:
  terraform:
    name: "Dry-run Terraform"
    if: inputs.apply == false || (github.event_name == 'release' && inputs.apply == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Terraform validate"
        run: |
          echo "environment: ${{ inputs.environment }}"
          echo "running 'terraform validate'..."
      - name: "Terraform plan"
        run: |
          echo "environment: ${{ inputs.environment }}"
          echo "running 'terraform plan'..."

  terraform_apply:
    name: "Apply Terraform"
    if: github.event_name == 'release' && inputs.apply == true
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: "Terraform validate"
        run: |
          echo "environment: ${{ inputs.environment }}"
          echo "running 'terraform validate'..."
      - name: "Terraform plan"
        run: |
          echo "environment: ${{ inputs.environment }}"
          echo "running 'terraform plan'..."
      - name: "Terraform apply"
        if: inputs.apply == 'true' && github.event.inputs.action == 'apply'
        run: |
          echo "environment: ${{ inputs.environment }}"
          echo "running 'terraform apply'..."
      - name: "Terraform destroy"
        if: inputs.apply == 'true' && github.event.inputs.action == 'destroy'
        run: |
          echo "environment: ${{ inputs.environment }}"
          echo "running 'terraform destroy'..."
