name: Deployment

on:
  release:
    types: [published]
  push:
    branches: ["main"]
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: ["main"]

jobs:
  plan_deploy_to_demo_environment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Terraform plan (demo environment)
        run: |
          echo "environment: ${{ env.ENVIRONMENT_NAME }}"
          echo "running 'terraform plan'..."


  deploy_to_demo_environment:
    if: github.event_name == 'release'

    runs-on: ubuntu-latest

    environment: demo

    steps:
      - uses: actions/checkout@v3

      - name: Terraform apply (demo environment)
        run: |
          echo "environment: ${{ env.ENVIRONMENT_NAME }}"
          echo "running 'terraform apply'..."
