name: Deploy

on:
  release:
    types: [published]
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  terraform_dryrun_demo:
    name: "[demo] Dry-run Terraform deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: demo
          action: apply
          apply: false

  terraform_apply_demo:
    name: "[demo] Apply Terraform deployment"
    needs: terraform_dryrun_demo
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: demo
          action: apply
          apply: true

  terraform_dryrun_prod:
    name: "[prod] Dry-run Terraform deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: prod
          action: apply
          apply: false

  terraform_apply_prod:
    name: "[prod] Apply Terraform deployment"
    needs:
      - terraform_apply_demo
      - terraform_dryrun_prod
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/actions/terraform"
        with:
          environment: prod
          action: apply
          apply: true
