name: release

on:
  release:
    types: [published]

jobs:
  create_deploy_pr:
    strategy:
      fail-fast: false
      matrix:
        environment:
          - demo
          - prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ matrix.environment }}"
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "${{ matrix.environment }}-promotion"
          token: ${{ secrets.GH_PAT }}
          title: "Deploy ${{ github.ref_name }} to ${{ matrix.environment }}"
          body: |
            Merging this PR will deploy ${{ github.ref_name }} to the **${{ matrix.environment }}** environment.
