name: release

on:
  release:
    types: [published]

jobs:
  create_deploy_pr:
    strategy:
      fail-fast: false
      matrix:
        environment:
          - demo
          - prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release branch
        run: |
          git branch "release-${{ github.ref_name }}"
          git push --set-upstream origin "release-${{ github.ref_name }}"

      - name: create pull request
        run: >
          gh pr create
          -B "${{ matrix.environment }}"
          -H "release-${{ github.ref_name }}"
          --title "Release ${{ github.ref_name }} to ${{ matrix.environment }}"
          --body "Merging this PR will deploy the branch 'release-${{ github.ref_name }}' to the **${{ matrix.environment }}** environment."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
