name: release-please

on:
  push:
    branches:
      - 'main'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: "date"

  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: package1
          token: ${{ secrets.GH_PAT }}

      # - id: create-release-branch
      #   uses: peterjgrainger/action-create-branch@v2.2.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      #   with:
      #     branch: "release-${{ steps.release.outputs.tag_name }}"
      #     sha: '${{ github.event.pull_request.head.sha }}'
