name: release-please

on:
  push:
    branches:
      - 'main'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: "date"

  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: package1
          token: ${{ secrets.GH_PAT }}

  create-release-branch:
    if: needs.release-please.outputs.releases_created == 'true'
    needs:
      - release-please
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      tag: "${{ needs.release-please.outputs.tag_name }}"
      branch: "release-${{ needs.release-please.outputs.tag_name }}"
    steps:
      - name: Create release branch
        run: |
          git branch ${{ env.branch }} ${{ env.tag }}
          git push --set-upstream origin ${{ env.branch }}
