name: Test Changes

on:
  pull_request:
    branches:
      - "main"
      - "demo"
      - "prod"
 
jobs:
  terraform:
    name: "terraform plan ${{ matrix.environment }}"
    uses: ./.github/workflows/reusable-terraform-workflow.yaml
    strategy:
      fail-fast: false
      matrix:
        environment:
          - dev
          - demo
          - prod
    with:
      environment: "${{ matrix.environment }}"
      action: "apply"
      apply: "false"
    secrets: inherit
