name: test

on:
  pull_request:
    branches:
      - "main"
      - "demo"
      - "prod"
 
jobs:
  create_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.script.outputs.matrix }}
    steps:
      - id: script
        run: |
          MATRIX='["dev", "demo", "prod"]'

          echo "::set-output name=matrix::${MATRIX}"

  terraform:
    name: "terraform plan ${{ matrix.environment }}"
    needs:
      - create_matrix
    uses: ./.github/workflows/reusable-terraform-workflow.yaml
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.create_matrix.outputs.matrix) }}
    with:
      environment: "${{ matrix.environment }}"
      action: "apply"
      apply: "false"
    secrets: inherit
