name: Test Changes

on:
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: bash

env:
  TF_VAR_EXOSCALE_API_KEY: '${{ secrets.TF_VAR_EXOSCALE_API_KEY }}'
  TF_VAR_EXOSCALE_API_SECRET: '${{ secrets.TF_VAR_EXOSCALE_API_SECRET }}'

  # renovate: datasource=github-releases depName=exoscale/cli
  EXO_CLI_VERSION: v1.74.3

  # renovate: datasource=github-releases depName=hashicorp/terraform
  TERRAFORM_VERSION: 1.4.1
  # x 1.5.7

  #

  # renovate: datasource=docker depName=ghcr.io/thomasstxyz/charts/fhb-mcce-aktt2-schuetz-k8s-helm/app
  AKTT2_PRIVATE_OCI_CHART_VERSION: 0.1.1

  # renovate: datasource=docker depName=ghcr.io/thomasstxyz/gitops-promotions-operator
  GOPRO_PUBLIC_DOCKER_IMAGE_VERSION: v0.1.1

  # renovate: datasource=github-tags depName=ansible/awx-operator
  AWX_OPERATOR_VERSION: 2.3.3

  #

  # renovate: datasource=github-tags depName=kubernetes/kubectl
  KUBECTL_VERSION: v1.21.2

  # test
  IAC_DEPLOY_KEY: '${{ secrets.IAC_DEPLOY_KEY }}'
      
jobs:
  terraform_plan:
    name: "terraform plan ${{ matrix.environment }}"
    strategy:
      fail-fast: false
      matrix:
        environment:
          - dev
          - demo
          - prod
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: "terraform plan ${{ matrix.environment }}"
        uses: "./.github/actions/terraform"
        with:
          environment: ${{ matrix.environment }}
          action: apply

          apply: false  # DO NOT CHANGE!

          ### Begin Copypasta env-vars
          TF_VAR_EXOSCALE_API_KEY: ${{ env.TF_VAR_EXOSCALE_API_KEY }}
          TF_VAR_EXOSCALE_API_SECRET: ${{ env.TF_VAR_EXOSCALE_API_SECRET }}
          ### End Copypasta env-vars
