name: test

on:
  pull_request:
    branches:
      - "main"
      - "demo"
      - "prod"
 
jobs:
  create_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.script.outputs.matrix }}
    steps:
      - id: script
        run: |
          MATRIX='["dev", "demo", "prod"]'

          if [ ${{ github.base_ref }} = "demo" ]; then
            MATRIX='["demo"]'
          fi

          if [ ${{ github.base_ref }} = "prod" ]; then
            MATRIX='["prod"]'
          fi

          echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT

  terraform:
    name: "terraform plan ${{ matrix.environment }}"
    needs:
      - create_matrix
    uses: ./.github/workflows/terraform.yaml
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.create_matrix.outputs.matrix) }}
    with:
      environment: "${{ matrix.environment }}"
      action: "apply"
      apply: "false"
    secrets: inherit
